### ISSUE TITLE
Build failure [Win 10, GCC v13.2]

### ISSUE THREAD

**Issue by SteveRussell33** [zachwieja/2LiftStudios#3]
```
g++ -std=c++17 -Wsuggest-override  -Isrc -Isrc/common -Isrc/components -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -funsafe-math-optimizations -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter -DARCH_X64 -march=nehalem -DARCH_WIN -D_USE_MATH_DEFINES -municode  -c -o build/src/modules/PolyQ.cpp.o src/modules/PolyQ.cpp
In file included from ../../include/helpers.hpp:11,
                 from ../../include/rack.hpp:35,
                 from src/plugin.hpp:5,
                 from src/modules/PolyQ.cpp:4:
../../include/app/SvgPanel.hpp: In member function 'void rack::app::ThemedSvgPanel::setBackground(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPanel.hpp:40:41: error: 'settings' has not been declared
   40 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
../../include/app/SvgPanel.hpp: In member function 'virtual void rack::app::ThemedSvgPanel::step()':
../../include/app/SvgPanel.hpp:44:41: error: 'settings' has not been declared
   44 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
In file included from ../../include/helpers.hpp:11,
                 from ../../include/rack.hpp:35,
                 from src/plugin.hpp:5,
                 from src/plugin.cpp:4:
../../include/app/SvgPanel.hpp: In member function 'void rack::app::ThemedSvgPanel::setBackground(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPanel.hpp:40:41: error: 'settings' has not been declared
   40 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
../../include/app/SvgPanel.hpp: In member function 'virtual void rack::app::ThemedSvgPanel::step()':
../../include/app/SvgPanel.hpp:44:41: error: 'settings' has not been declared
   44 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
In file included from ../../include/helpers.hpp:11,
                 from ../../include/rack.hpp:35,
                 from src/plugin.hpp:5,
                 from src/modules/Comps.cpp:4:
../../include/app/SvgPanel.hpp: In member function 'void rack::app::ThemedSvgPanel::setBackground(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPanel.hpp:40:41: error: 'settings' has not been declared
   40 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
../../include/app/SvgPanel.hpp: In member function 'virtual void rack::app::ThemedSvgPanel::step()':
../../include/app/SvgPanel.hpp:44:41: error: 'settings' has not been declared
   44 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
In file included from ../../include/helpers.hpp:11,
                 from ../../include/rack.hpp:35,
                 from src/plugin.hpp:5,
                 from src/modules/Merge.cpp:4:
../../include/app/SvgPanel.hpp: In member function 'void rack::app::ThemedSvgPanel::setBackground(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPanel.hpp:40:41: error: 'settings' has not been declared
   40 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
../../include/app/SvgPanel.hpp: In member function 'virtual void rack::app::ThemedSvgPanel::step()':
../../include/app/SvgPanel.hpp:44:41: error: 'settings' has not been declared
   44 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:6,
                 from ../../include/rack.hpp:36:
../../include/app/SvgPort.hpp: In member function 'void rack::app::ThemedSvgPort::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPort.hpp:37:33: error: 'settings' has not been declared
   37 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
../../include/app/SvgPort.hpp: In member function 'virtual void rack::app::ThemedSvgPort::step()':
../../include/app/SvgPort.hpp:41:33: error: 'settings' has not been declared
   41 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:9:
../../include/app/SvgScrew.hpp: In member function 'void rack::app::ThemedSvgScrew::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgScrew.hpp:33:34: error: 'settings' has not been declared
   33 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
../../include/app/SvgScrew.hpp: In member function 'virtual void rack::app::ThemedSvgScrew::step()':
../../include/app/SvgScrew.hpp:37:34: error: 'settings' has not been declared
   37 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:6,
                 from ../../include/rack.hpp:36:
../../include/app/SvgPort.hpp: In member function 'void rack::app::ThemedSvgPort::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPort.hpp:37:33: error: 'settings' has not been declared
   37 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:6,
                 from ../../include/rack.hpp:36:
../../include/app/SvgPort.hpp: In member function 'void rack::app::ThemedSvgPort::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPort.hpp:37:33: error: 'settings' has not been declared
   37 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
../../include/app/SvgPort.hpp: In member function 'virtual void rack::app::ThemedSvgPort::step()':
../../include/app/SvgPort.hpp:41:33: error: 'settings' has not been declared
   41 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
../../include/app/SvgPort.hpp: In member function 'virtual void rack::app::ThemedSvgPort::step()':
../../include/app/SvgPort.hpp:41:33: error: 'settings' has not been declared
   41 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:6,
                 from ../../include/rack.hpp:36:
../../include/app/SvgPort.hpp: In member function 'void rack::app::ThemedSvgPort::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPort.hpp:37:33: error: 'settings' has not been declared
   37 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
../../include/app/SvgPort.hpp: In member function 'virtual void rack::app::ThemedSvgPort::step()':
../../include/app/SvgPort.hpp:41:33: error: 'settings' has not been declared
   41 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:9:
../../include/app/SvgScrew.hpp: In member function 'void rack::app::ThemedSvgScrew::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgScrew.hpp:33:34: error: 'settings' has not been declared
   33 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:9:
../../include/app/SvgScrew.hpp: In member function 'void rack::app::ThemedSvgScrew::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgScrew.hpp:33:34: error: 'settings' has not been declared
   33 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
../../include/app/SvgScrew.hpp: In member function 'virtual void rack::app::ThemedSvgScrew::step()':
../../include/app/SvgScrew.hpp:37:34: error: 'settings' has not been declared
   37 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
../../include/app/SvgScrew.hpp: In member function 'virtual void rack::app::ThemedSvgScrew::step()':
../../include/app/SvgScrew.hpp:37:34: error: 'settings' has not been declared
   37 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:9:
../../include/app/SvgScrew.hpp: In member function 'void rack::app::ThemedSvgScrew::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgScrew.hpp:33:34: error: 'settings' has not been declared
   33 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
../../include/app/SvgScrew.hpp: In member function 'virtual void rack::app::ThemedSvgScrew::step()':
../../include/app/SvgScrew.hpp:37:34: error: 'settings' has not been declared
   37 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
make: *** [../../compile.mk:89: build/src/plugin.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [../../compile.mk:89: build/src/modules/Merge.cpp.o] Error 1
make: *** [../../compile.mk:89: build/src/modules/Comps.cpp.o] Error 1
make: *** [../../compile.mk:89: build/src/modules/PolyQ.cpp.o] Error 1
```

**Comment by zachwieja** [comment]
Thanks Steve,  I super appreciate someone keeping me honest.  I still haven't upgraded GCC.  I am busy for the next week. Will upgrade and let you know once I commit a fix.


_sjz.
________________________________
From: Steve Russell ***@***.***>
Sent: Friday, November 24, 2023 5:01:31 AM
To: zachwieja/2LiftStudios ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [zachwieja/2LiftStudios] Build failure [Win 10, GCC v13.2] (Issue #3)


g++ -std=c++17 -Wsuggest-override  -Isrc -Isrc/common -Isrc/components -fPIC -I../../include -I../../dep/include -MMD -MP -g -O3 -funsafe-math-optimizations -fno-omit-frame-pointer -Wall -Wextra -Wno-unused-parameter -DARCH_X64 -march=nehalem -DARCH_WIN -D_USE_MATH_DEFINES -municode  -c -o build/src/modules/PolyQ.cpp.o src/modules/PolyQ.cpp
In file included from ../../include/helpers.hpp:11,
                 from ../../include/rack.hpp:35,
                 from src/plugin.hpp:5,
                 from src/modules/PolyQ.cpp:4:
../../include/app/SvgPanel.hpp: In member function 'void rack::app::ThemedSvgPanel::setBackground(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPanel.hpp:40:41: error: 'settings' has not been declared
   40 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
../../include/app/SvgPanel.hpp: In member function 'virtual void rack::app::ThemedSvgPanel::step()':
../../include/app/SvgPanel.hpp:44:41: error: 'settings' has not been declared
   44 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
In file included from ../../include/helpers.hpp:11,
                 from ../../include/rack.hpp:35,
                 from src/plugin.hpp:5,
                 from src/plugin.cpp:4:
../../include/app/SvgPanel.hpp: In member function 'void rack::app::ThemedSvgPanel::setBackground(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPanel.hpp:40:41: error: 'settings' has not been declared
   40 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
../../include/app/SvgPanel.hpp: In member function 'virtual void rack::app::ThemedSvgPanel::step()':
../../include/app/SvgPanel.hpp:44:41: error: 'settings' has not been declared
   44 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
In file included from ../../include/helpers.hpp:11,
                 from ../../include/rack.hpp:35,
                 from src/plugin.hpp:5,
                 from src/modules/Comps.cpp:4:
../../include/app/SvgPanel.hpp: In member function 'void rack::app::ThemedSvgPanel::setBackground(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPanel.hpp:40:41: error: 'settings' has not been declared
   40 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
../../include/app/SvgPanel.hpp: In member function 'virtual void rack::app::ThemedSvgPanel::step()':
../../include/app/SvgPanel.hpp:44:41: error: 'settings' has not been declared
   44 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
In file included from ../../include/helpers.hpp:11,
                 from ../../include/rack.hpp:35,
                 from src/plugin.hpp:5,
                 from src/modules/Merge.cpp:4:
../../include/app/SvgPanel.hpp: In member function 'void rack::app::ThemedSvgPanel::setBackground(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPanel.hpp:40:41: error: 'settings' has not been declared
   40 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
../../include/app/SvgPanel.hpp: In member function 'virtual void rack::app::ThemedSvgPanel::step()':
../../include/app/SvgPanel.hpp:44:41: error: 'settings' has not been declared
   44 |                 SvgPanel::setBackground(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                         ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:6,
                 from ../../include/rack.hpp:36:
../../include/app/SvgPort.hpp: In member function 'void rack::app::ThemedSvgPort::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPort.hpp:37:33: error: 'settings' has not been declared
   37 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
../../include/app/SvgPort.hpp: In member function 'virtual void rack::app::ThemedSvgPort::step()':
../../include/app/SvgPort.hpp:41:33: error: 'settings' has not been declared
   41 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:9:
../../include/app/SvgScrew.hpp: In member function 'void rack::app::ThemedSvgScrew::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgScrew.hpp:33:34: error: 'settings' has not been declared
   33 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
../../include/app/SvgScrew.hpp: In member function 'virtual void rack::app::ThemedSvgScrew::step()':
../../include/app/SvgScrew.hpp:37:34: error: 'settings' has not been declared
   37 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:6,
                 from ../../include/rack.hpp:36:
../../include/app/SvgPort.hpp: In member function 'void rack::app::ThemedSvgPort::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPort.hpp:37:33: error: 'settings' has not been declared
   37 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:6,
                 from ../../include/rack.hpp:36:
../../include/app/SvgPort.hpp: In member function 'void rack::app::ThemedSvgPort::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPort.hpp:37:33: error: 'settings' has not been declared
   37 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
../../include/app/SvgPort.hpp: In member function 'virtual void rack::app::ThemedSvgPort::step()':
../../include/app/SvgPort.hpp:41:33: error: 'settings' has not been declared
   41 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
../../include/app/SvgPort.hpp: In member function 'virtual void rack::app::ThemedSvgPort::step()':
../../include/app/SvgPort.hpp:41:33: error: 'settings' has not been declared
   41 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:6,
                 from ../../include/rack.hpp:36:
../../include/app/SvgPort.hpp: In member function 'void rack::app::ThemedSvgPort::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgPort.hpp:37:33: error: 'settings' has not been declared
   37 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
../../include/app/SvgPort.hpp: In member function 'virtual void rack::app::ThemedSvgPort::step()':
../../include/app/SvgPort.hpp:41:33: error: 'settings' has not been declared
   41 |                 SvgPort::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                 ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:9:
../../include/app/SvgScrew.hpp: In member function 'void rack::app::ThemedSvgScrew::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgScrew.hpp:33:34: error: 'settings' has not been declared
   33 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:9:
../../include/app/SvgScrew.hpp: In member function 'void rack::app::ThemedSvgScrew::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgScrew.hpp:33:34: error: 'settings' has not been declared
   33 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
../../include/app/SvgScrew.hpp: In member function 'virtual void rack::app::ThemedSvgScrew::step()':
../../include/app/SvgScrew.hpp:37:34: error: 'settings' has not been declared
   37 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
../../include/app/SvgScrew.hpp: In member function 'virtual void rack::app::ThemedSvgScrew::step()':
../../include/app/SvgScrew.hpp:37:34: error: 'settings' has not been declared
   37 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
In file included from ../../include/componentlibrary.hpp:9:
../../include/app/SvgScrew.hpp: In member function 'void rack::app::ThemedSvgScrew::setSvg(std::shared_ptr<rack::window::Svg>, std::shared_ptr<rack::window::Svg>)':
../../include/app/SvgScrew.hpp:33:34: error: 'settings' has not been declared
   33 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
../../include/app/SvgScrew.hpp: In member function 'virtual void rack::app::ThemedSvgScrew::step()':
../../include/app/SvgScrew.hpp:37:34: error: 'settings' has not been declared
   37 |                 SvgScrew::setSvg(settings::preferDarkPanels ? darkSvg : lightSvg);
      |                                  ^~~~~~~~
make: *** [../../compile.mk:89: build/src/plugin.cpp.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [../../compile.mk:89: build/src/modules/Merge.cpp.o] Error 1
make: *** [../../compile.mk:89: build/src/modules/Comps.cpp.o] Error 1
make: *** [../../compile.mk:89: build/src/modules/PolyQ.cpp.o] Error 1

**Comment by zachwieja** [comment]
I updated my build environment (not INKSCAPE) but everything else.  I was able to reproduce the problem with the newer compiler and vcvrack SDK.  I renamed one compilation unit to avoid conflict with vcvrack, and then added some additional include statements to satisfy the stricter compiler.   I believe this issue is resolved.   If you confirm, then I will close.  Thanks again for your help.

**Comment by SteveRussell33** [comment]
Can confirm that commit is good. Although I did comment out the ``all`` target in ``makefile`` as that still threw up errors
```
Failed to register: Timeout was reached
make: *** [Makefile:49: build/res/Merge.svg] Error 1
make: *** Waiting for unfinished jobs....
```
Not sure why it does that - newer version? Anyway, the plugin build part works so I'll close this issue as completed.

**Comment by zachwieja** [comment]
That is because I use INKSCAPE to change all the SVG text objects into paths.

If you don't have INKSCAPE it fails.  I suppose I can make the the .svg targets conditional based on the definition of INKSCAPE.

And then even if you define INKSCAPE I need to find the modern incantation for those commands which I believe they changed so my scripts don't work with a modern version, depending on the version does weird stuff like not returning to the makefile

_sjz.
________________________________
